### PR TITLE
Updating image processing

### PR DESCRIPTION
**Pull request by tristanwagner**
Switching to Firefox Geckodriver to allow screenshoting directly the Tooltip
element within hidden window
Added link to item with image

### CODE REVIEW

**Comment by TomHaii** [comment]
Thanks for the pull request, efficiency improvements.

**Comment by tristanwagner** [comment]
You are welcome, I thought about other improvements possible like !findplayer with server option and caching images of item resquest, what do you think about it?

**Comment by TomHaii** [comment]
Yes, adding server option with !findplayer sounds like a great idea.
And by catching image of item request, do you mean the icon or the actual look of the item in an in-game screenshot? (can probably grab one from vanillagaming).

**Comment by tristanwagner** [comment]
I said caching not catching, like make a /items directory with all the screenshot of item already requested saved instead of deleting them, and search in it before sending the http request. It will be a lot more faster for item already requested.

Could also make an option to enable or disable cache if you don't want to keep the screenshots.

You can add me on discord at Payki#6529 if you want to discuss more about it.

**Comment by TomHaii** [comment]
Sorry, long day.
Sound like a good idea, I am adding you to discord, we can talk about it tomorrow.

**Pull request merged**
